apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/rancher/local-path-provisioner.git
      targetRevision: v0.0.24
      path: deploy/chart/local-path-provisioner
      helm:
        valueFiles:
          - $values/values/local-path-provisioner.yaml
    - repoURL: https://github.com/sumit-ini8labs/Argocd-deployment.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
