apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.14
    helm:
      values: |
        replicas: 1
        mode: standalone
        persistence:
          enabled: true
          size: 10Gi
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
        service:
          type: NodePort
        consoleService:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
